# Generated by Django 5.0.6 on 2024-06-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_cart_customer_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
