from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from ecom import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('add-to-cart/<int:pk>/', views.add_to_cart_view, name='add-to-cart'),
    path('admin-add-product/', views.admin_add_product_view, name='admin-add-product'),
    path('admin-dashboard/', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-products/', views.admin_products_view, name='admin-products'),
    path('admin-view-booking/', views.admin_view_booking_view, name='admin-view-booking'),
    path('adminclick/', views.adminclick_view, name='adminclick'),
    path('adminlogin/', LoginView.as_view(template_name='ecom/adminlogin.html'), name='adminlogin'),
    path('afterlogin/', views.afterlogin_view, name='afterlogin'),
    path('cart/', views.cart_view, name='cart'),
    path('contactus/', views.send_feedback_view, name='contactus'),
    path('customer-address/', views.customer_address_view, name='customer-address'),
    path('customer-home/', views.customer_home_view, name='customer_home'),
    path('customerlogin/', LoginView.as_view(template_name='ecom/customer/customerlogin.html'), name='customerlogin'),
    path('customersignup/', views.customer_signup_view, name='customersignup'),
    path('delete-customer/<int:pk>/', views.delete_customer_view, name='delete-customer'),
    path('delete-order/<int:pk>/', views.delete_order_view, name='delete-order'),
    path('delete-product/<int:pk>/', views.delete_product_view, name='delete-product'),
    path('download-invoice/<int:orderID>/<int:productID>/', views.download_invoice_view, name='download-invoice'),
    path('edit-profile/', views.edit_profile_view, name='edit_profile'),
    path('logout/', LogoutView.as_view(template_name='ecom/homepage/logout.html'), name='logout'),
    path('my-order/', views.my_order_view, name='my_order'),
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('payment-success/', views.payment_success_view, name='payment_success'),
    path('products/', views.product_display, name='product_display'),
    path('products/<int:pk>/', views.product_detail_view, name='product_detail'),
    path('products/category/<str:category>/', views.product_by_category, name='product_by_category'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart_view, name='remove-from-cart'),
    path('search/', views.search_view, name='search'),
    path('update-customer/<int:pk>/', views.update_customer_view, name='update-customer'),
    path('update-order/<int:pk>/', views.update_order_view, name='update-order'),
    path('update-product/<int:pk>/', views.update_product_view, name='update-product'),
    path('view-customer/', views.view_customer_view, name='view-customer'),
    path('view-feedback/', views.view_feedback_view, name='view-feedback'),
]
